test('should fail', () => { throw new Error('Test error'); });
